# Generated by Django 3.0.4 on 2020-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='books', verbose_name='Книга')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('order', models.IntegerField(verbose_name='Последовательность отображения')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='booklets/files', verbose_name='Буклет')),
                ('preview',
                 models.ImageField(blank=True, null=True, upload_to='booklets/previews', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('order', models.IntegerField(verbose_name='Последовательность отображения')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Буклет',
                'verbose_name_plural': 'Буклеты',
                'db_table': 'booklets',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents', verbose_name='Документ для блока прямая речь')),
                ('title', models.CharField(max_length=50, verbose_name='Название документа')),
                ('text', models.CharField(max_length=150, verbose_name='Текст-описание документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Infographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='infographics/files', verbose_name='Буклет')),
                ('preview',
                 models.ImageField(blank=True, null=True, upload_to='infographics/previews', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('order', models.IntegerField(verbose_name='Последовательность отображения')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Инфографика',
                'verbose_name_plural': 'Инфографики',
                'db_table': 'infographics',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='magazines', verbose_name='Журнал')),
                ('description', models.TextField(verbose_name='Описание журнала')),
                ('publication', models.DateField(verbose_name='Дата выпуска')),
                ('publishing_house', models.CharField(max_length=100, verbose_name='Издательство')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
                ('name', models.CharField(max_length=100, verbose_name='Название журнала')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'db_table': 'magazines',
            },
        ),
        migrations.CreateModel(
            name='PhotoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos', verbose_name='Изображения фотокарточки')),
                ('date', models.DateField(verbose_name='Дата создания изображения')),
                ('sub_title', models.CharField(max_length=70, verbose_name='Краткое описание фотокарточки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Полное описание фотокарточки')),
            ],
            options={
                'verbose_name': 'Фотокарточка',
                'verbose_name_plural': 'Фотокарточки',
                'db_table': 'photo_cards',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/files', verbose_name='Видео прямой речи')),
                ('img', models.ImageField(upload_to='videos/previews', verbose_name='Картинка-превью для видео')),
                ('text', models.CharField(max_length=65, verbose_name='Краткое описание видео')),
            ],
            options={
                'verbose_name': 'Видео запись',
                'verbose_name_plural': 'Видео записи',
                'db_table': 'videos',
            },
        ),
    ]
